---
title: "Data Processing"
output: html_notebook
---

```{r}
# libraries
library(data.table)
library(tidyverse)

# load data
ss_raw <- fread("Data/SesameStreetData.csv")
```

```{r}
# create response variables
ss <-
  ss_raw %>%
  mutate(percnumb = (postnumb - prenumb)*100/prenumb,
         perclet = (postlet - prelet)*100/prelet,
         percbody = (postbody - prebody)*100/prebody) %>%
  select(id, site, sex, age, viewcat, setting, peabody, encour, regular,
         prenumb, postnumb, percnumb, 
         prelet, postlet, perclet, 
         prebody, postbody, percbody) %>%
  mutate(percnumb = replace(percnumb, percnumb==1200, NA)) # Set 1200 score to NA


```

```{r}
saveRDS(ss, file = "Data/ss.RDS")
```

```{r}
# Create response variables, including the divided by max
# Keep the outlier for pure percent increase
ss_all <-
  ss_raw %>%
  mutate(percnumb = (postnumb - prenumb)*100/prenumb,
         perclet = (postlet - prelet)*100/prelet,
         percbody = (postbody - prebody)*100/prebody) %>%
  mutate(percnumb_max = (postnumb - prenumb)*100/54,
         perclet_max = (postlet - prelet)*100/58,
         percbody_max = (postbody - prebody)*100/32) %>%
  select(id, site, sex, age, viewcat, setting, 
         peabody, encour, regular,
         prenumb, postnumb, percnumb, percnumb_max,
         prelet, postlet, perclet, perclet_max,
         prebody, postbody, percbody, percbody_max) 
```

```{r}
saveRDS(ss_all, file = "Data/ss_all.RDS")
```
